commands:
  innovus: genus -no_gui -batch

scheduler:
  type: lsf
  queue: eda_queue
  project: eda_project
  resource_spec: "select[mem>16G] rusage[mem=16G] span[hosts=eda_nodes]"

session_dir: ./sessions
heartbeat_interval_s: 5.0
enable_lease: true
